import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Basir',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Puma',
        logo: '/images/logo1.png',
        description: 'best seller',
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: 'https://images.unsplash.com/photo-1596755094514-f87e32f85e23?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=80',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality slim shirt',
    },
    {
      name: 'Adidas Fit Shirt',
      category: 'Shirts',
      image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=80',
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'comfortable fit shirt',
    },
    {
      name: 'Lacoste Free Shirt',
      category: 'Shirts',
      image: 'https://images.unsplash.com/photo-1574180566232-aaad1b5b8450?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=80',
      price: 220,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'premium free shirt',
    },
    {
      name: 'Guess Cotton T-Shirt',
      category: 'Shirts',
      image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=80',
      price: 45,
      countInStock: 50,
      brand: 'Guess',
      rating: 4.1,
      numReviews: 21,
      description: '100% cotton casual t-shirt',
    },
    {
      name: 'Armani Silk Shirt',
      category: 'Shirts',
      image: 'https://images.unsplash.com/photo-1602810317536-5d5e8a552d15?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=80',
      price: 180,
      countInStock: 25,
      brand: 'Armani',
      rating: 4.7,
      numReviews: 19,
      description: 'Comfortable silk shirt for evenings',
    },
    {
      name: 'Nike Slim Pant',
      category: 'Pants',
      image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=80',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality slim pant',
    },
    {
      name: 'Puma Slim Pant',
      category: 'Pants',
      image: 'https://images.unsplash.com/photo-1555689502-c4b22d76c56f?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=80',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'comfortable sport pant',
    },
    {
      name: 'Adidas Fit Pant',
      category: 'Pants',
      image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=80',
      price: 139,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: 'best fitting pants',
    },
    {
      name: 'Levi\'s Denim Jeans',
      category: 'Pants',
      image: 'https://images.unsplash.com/photo-1542272601-5272a281005f?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=80',
      price: 85,
      countInStock: 14,
      brand: 'Levi\'s',
      rating: 4.4,
      numReviews: 32,
      description: 'Durable and comfortable blue denim jeans',
    },
    {
      name: 'Zara Summer Dress',
      category: 'Dresses',
      image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=80',
      price: 150,
      countInStock: 8,
      brand: 'Zara',
      rating: 4.6,
      numReviews: 8,
      description: 'Elegant summer dress for casual wear',
    },
    {
      name: 'H&M Summer Dress',
      category: 'Dresses',
      image: 'https://images.unsplash.com/photo-1572804013309-84a8fbbbc2c6?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=80',
      price: 120,
      countInStock: 10,
      brand: 'H&M',
      rating: 4.4,
      numReviews: 15,
      description: 'Red casual dress',
    },
    {
      name: 'H&M Classic Jacket',
      category: 'Jackets',
      image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=80',
      price: 210,
      countInStock: 4,
      brand: 'H&M',
      rating: 4.3,
      numReviews: 5,
      description: 'Warm and stylish winter jacket',
    },
    {
      name: 'Zara Leather Jacket',
      category: 'Jackets',
      image: 'https://images.unsplash.com/photo-1520975954732-57dd22299614?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=80',
      price: 280,
      countInStock: 7,
      brand: 'Zara',
      rating: 4.8,
      numReviews: 12,
      description: 'Classic black leather jacket',
    },
    {
      name: 'Puma Running Shoes',
      category: 'Shoes',
      image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=80',
      price: 90,
      countInStock: 30,
      brand: 'Puma',
      rating: 4.7,
      numReviews: 45,
      description: 'Lightweight running shoes for all terrains',
    },
    {
      name: 'Nike Air Max',
      category: 'Shoes',
      image: 'https://images.unsplash.com/photo-1605348532760-6753d2c43329?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=80',
      price: 145,
      countInStock: 22,
      brand: 'Nike',
      rating: 4.9,
      numReviews: 80,
      description: 'Classic Nike Air Max with extra cushioning',
    },
    {
      name: 'Gucci Leather Belt',
      category: 'Accessories',
      image: 'https://images.unsplash.com/photo-1624222247344-550fb60583dc?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=80',
      price: 450,
      countInStock: 10,
      brand: 'Gucci',
      rating: 4.8,
      numReviews: 12,
      description: 'Premium black leather belt with gold GG buckle',
    },
    {
      name: 'Gucci Formal Suit',
      category: 'Suits',
      image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=80',
      price: 1500,
      countInStock: 3,
      brand: 'Gucci',
      rating: 5.0,
      numReviews: 4,
      description: 'Luxury Italian formal suit',
    },
    {
      name: 'Armani Exchange Watch',
      category: 'Accessories',
      image: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=80',
      price: 250,
      countInStock: 15,
      brand: 'Armani',
      rating: 4.5,
      numReviews: 42,
      description: 'Elegant stainless steel watch',
    },
    {
      name: 'Sony WH-1000XM4 Headphones',
      category: 'Electronics',
      image: 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=80',
      price: 348,
      countInStock: 25,
      brand: 'Sony',
      rating: 4.8,
      numReviews: 245,
      description: 'Industry leading noise canceling wireless headphones',
    },
    {
      name: 'Apple MacBook Pro M2',
      category: 'Electronics',
      image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=80',
      price: 1999,
      countInStock: 5,
      brand: 'Apple',
      rating: 4.9,
      numReviews: 120,
      description: 'Powerful laptop for professionals',
    },
    {
      name: 'Samsung 4K Smart TV',
      category: 'Electronics',
      image: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=80',
      price: 899,
      countInStock: 8,
      brand: 'Samsung',
      rating: 4.7,
      numReviews: 89,
      description: 'Ultra HD smart TV with vibrant colors',
    },
    {
      name: 'Herschel Classic Backpack',
      category: 'Bags',
      image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=80',
      price: 55,
      countInStock: 18,
      brand: 'Herschel',
      rating: 4.6,
      numReviews: 54,
      description: 'A timeless silhouette perfect for everyday use',
    },
    {
      name: 'Louis Vuitton Handbag',
      category: 'Bags',
      image: 'https://images.unsplash.com/photo-1584916201218-f4242ceb4809?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=80',
      price: 1850,
      countInStock: 3,
      brand: 'Louis Vuitton',
      rating: 4.9,
      numReviews: 14,
      description: 'Classic monogram canvas handbag',
    },
    {
      name: 'Ray-Ban Aviator Sunglasses',
      category: 'Accessories',
      image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=80',
      price: 160,
      countInStock: 40,
      brand: 'Ray-Ban',
      rating: 4.7,
      numReviews: 211,
      description: 'Timeless tear-drop aviator sunglasses',
    },
    {
      name: 'Yankees Baseball Cap',
      category: 'Hats',
      image: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=80',
      price: 35,
      countInStock: 60,
      brand: 'New Era',
      rating: 4.5,
      numReviews: 76,
      description: 'Classic NY Yankees adjustable cap',
    },
    {
      name: 'Chanel No. 5 Perfume',
      category: 'Beauty',
      image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=80',
      price: 135,
      countInStock: 12,
      brand: 'Chanel',
      rating: 4.9,
      numReviews: 180,
      description: 'Iconic feminine floral fragrance',
    },
    {
      name: 'Rolex Submariner',
      category: 'Watches',
      image: 'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=80',
      price: 9500,
      countInStock: 2,
      brand: 'Rolex',
      rating: 5.0,
      numReviews: 9,
      description: 'Legendary diving watch with oyster steel',
    }
  ],
};
export default data;
